#cloud-config
users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHT6zHTr+4oX12BeMbvdfnVgOGPmiT+TvUsE1yq+r3ct alavidze@VM1

package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - jq
  - htop
  - git

ssh_pwauth: false

runcmd:
  - echo "Cloud-init completed" > /var/log/cloud-init-custom.log