apiVersion: apps/v1
kind: Deployment
metadata:
  name: diploma-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diploma-app
  template:
    metadata:
      labels:
        app: diploma-app
    spec:
      imagePullSecrets:
        - name: yc-registry-secret
      containers:
        - name: diploma-app
          image: cr.yandex/crpqln2v62k74h8f7hqa/app:75e274abb6a2cfc9403efbbdbd2339019aa6fcab
          ports:
            - containerPort: 80
